[package]
name = "hello-world-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
log = "0.4.26"
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
